# Generated by Django 4.2.15 on 2024-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdoctor',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar_media'),
            preserve_default=False,
        ),
    ]
