# Generated by Django 4.2.15 on 2024-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eh_admin', '0002_healthtips'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuraceBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
