# Generated by Django 4.2.15 on 2024-09-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpatient',
            old_name='next_field',
            new_name='next_date',
        ),
    ]
