# Generated by Django 4.2.15 on 2024-09-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_next_field_checkpatient_next_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpatient',
            name='diagnose',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
