# Generated by Django 4.2.15 on 2024-09-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_checkpatient_diagnose'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
