# Generated by Django 4.2.15 on 2024-09-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_checkpatient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpatient',
            name='total_amnt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
