# Generated by Django 4.2.15 on 2024-09-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eh_admin', '0003_insuracebrand'),
        ('patient', '0006_checkpatient_total_amnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=200, unique=True)),
                ('member_name', models.CharField(max_length=200)),
                ('ins_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eh_admin.insuracebrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientregistration')),
            ],
        ),
    ]
