# Generated by Django 4.2.15 on 2024-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patientinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
