# Generated by Django 4.2.15 on 2024-09-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patientinsurance_is_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinsurance',
            old_name='user',
            new_name='patient',
        ),
    ]
