# Generated by Django 4.2.15 on 2024-09-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_rename_user_patientinsurance_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinsurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
